name: CI

on:
  push:
    tags: [v*]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: make dist
    - uses: softprops/action-gh-release@v1
      with:
        files: dist/!(config.yaml)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: superbrothers/actions/krew-plugin-test@master
      with:
        manifest: ./dist/open-svc.yaml
        command: kubectl open-svc --help
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
    - uses: actions/checkout@v2
      with:
        repository: superbrothers/krew-index
        path: krew-index
        fetch-depth: 0
    - run: cp dist/open-svc.yaml krew-index/plugins
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        path: krew-index
        push-to-fork: superbrothers-sandbox/krew-index
        commit-message: Bump the version of open-svc to ${{ steps.get_version.outputs.VERSION }}
        title: Bump the version of open-svc to ${{ steps.get_version.outputs.VERSION }}
        body: This PR bumps the version of open-svc to ${{ steps.get_version.outputs.VERSION }}.
        branch: open-svc-${{ steps.get_version.outputs.VERSION }}
