name: Release

on:
  push:
    tags: [v*]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: make dist
    - uses: softprops/action-gh-release@v1
      with:
        files: dist/!(config.yaml)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: superbrothers/actions/krew-plugin-test@master
      with:
        manifest: ./dist/open-svc.yaml
        command: kubectl open-svc --help
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
    - uses: superbrothers/actions/krew-plugin-release@krew-plugin-release
      with:
        token: ${{ secrets.PAT }}
        plugin_name: open-svc
        manifest_path: dist/open-svc.yaml
        git_author_name: superbrothers-robot
        git_author_email: superbrothers-robot@users.noreply.github.com
        krew_index_repo: superbrothers/krew-index
